### ISSUE TITLE
Не ставится через pip

### ISSUE THREAD

**Issue by Atorich** [glibin/tortik#16]
Лог:
```
Install packages failed: Error occurred when installing package tortik. 

The following command was executed:

packaging_tool.py install --build-dir /tmp/pycharm-packaging2166950156034870962.tmp tortik

The error output of the command:


Downloading/unpacking tortik
  Could not find any downloads that satisfy the requirement tortik
Cleaning up...
No distributions at all found for tortik
Storing complete log in /home/ator/.pip/pip.log
```

```
Exception information:
Traceback (most recent call last):
  File "/home/ator/venv/oblichi-front/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/ator/venv/oblichi-front/local/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/ator/venv/oblichi-front/local/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/ator/venv/oblichi-front/local/lib/python2.7/site-packages/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for tortik
```

**Comment by glibin** [comment]
На данный момент пакет доступен в тестовом PyPi.

Информация по установке из тестового PyPi: https://wiki.python.org/moin/TestPyPI

**Comment by glibin** [comment]
Уже какое-то время доступен в PyPi: https://pypi.python.org/pypi/tortik
